[versions]
paper-api = "1.21.4-R0.1-SNAPSHOT"
surf-database = "1.0.4-SNAPSHOT"
luckperms-api = "5.4"

[libraries]
surf-database = { module = "dev.slne.surf:surf-database", version.ref = "surf-database" }
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
luckperms-api = { module = "net.luckperms:api", version.ref = "luckperms-api" }