cross-server-messages:
  current-server: "lobby01" # the internal server name, configured in the velocity config
  current-server-name: "Lobby 1" # the display name of the server
  forward-to:
    - "lobby02"
    - "lobby03"
connection:
  messages:
    enabled: true
    join: ""
    leave: ""

chat-message-of-the-day-status: false
chat-message-of-the-day:
  lines:
    - "<darK_gray>*--------------------------------------------------*"
    - " "
    - "<white>Willkommen auf dem <#f9c353><st>CastCrafter Community Server</st><white>!"
    - " "
    - "<#96CFE8>Alle Informationen, inklusive der Serverregeln, findest du auf:"
    - "<#4BB9F9>https://castcrafter.de/server"
    - " "
    - " "
    - "<dark_gray>*--------------------------------------------------*"

spam-protection:
  max-messages: 5
  in-seconds: 1